import { contentResponse } from "../types/course-detail";

export const ContentData: contentResponse[] = [
  {
    _id: "CNT001",
    cntType: "quiz",
    tagname: "Incomplete",
    title: "Math Basics Quiz",
    descriptions: "This quiz tests core arithmetic skills such as addition, subtraction, multiplication, and division. It also includes basic algebraic expressions and simple word problems.",
    time: "2025-06-05 9:00AM",
  },
  {
    _id: "CNT002",
    cntType: "quiz",
    tagname: "Submitted",
    title: "Science - Chapter 1",
    descriptions: "Covers the foundational concepts from Chapter 1, including matter, states of matter, and scientific tools.",
    time: "2025-06-05 10:30AM",
  },
  {
    _id: "CNT003",
    cntType: "quiz",
    tagname: "Overdue",
    title: "History Timeline Test",
    descriptions: "A chronological test on key world events, significant historical figures, and ancient civilizations.",
    time: "2025-06-04 11:15AM",
  },
  {
    _id: "CNT004",
    cntType: "quiz",
    tagname: "Incomplete",
    title: "Geography Pop Quiz",
    descriptions: "A quick quiz to assess knowledge on world continents, oceans, and prominent landmarks like the Great Wall and Amazon River.",
    time: "2025-06-06 12:00PM",
  },
  {
    _id: "CNT005",
    cntType: "quiz",
    tagname: "Submitted",
    title: "Biology - Cell Structure",
    descriptions: "This detailed quiz focuses on the components of plant and animal cells, their functions, and how they interact. Includes diagrams and labeling questions.",
    time: "2025-06-07 1:45PM",
  },
  {
    _id: "CNT006",
    cntType: "assignment",
    tagname: "Submitted",
    title: "Assignment 1: DOM Manipulation",
    descriptions: "Build a simple webpage that responds to user interactions using JavaScript DOM APIs.",
    time: "2025-06-10 11:59PM",
  },
  {
    _id: "CNT007",
    cntType: "assignment",
    tagname: "Todo",
    title: "Assignment 2: CSS Flexbox Layout",
    descriptions: "Create a responsive layout using CSS Flexbox to arrange content blocks in various screen sizes.",
    time: "2025-06-12 11:59PM",
  },
  {
    _id: "CNT008",
    cntType: "assignment",
    tagname: "Overdue",
    title: "Assignment 3: JavaScript Functions",
    descriptions: "Write several JavaScript functions to manipulate arrays and strings based on provided requirements.",
    time: "2025-06-08 11:59PM",
  },
  {
    _id: "CNT009",
    cntType: "assignment",
    tagname: "Submitted",
    title: "Assignment 4: HTML Forms & Validation",
    descriptions: "Design a registration form with input validation using both HTML5 and JavaScript.",
    time: "2025-06-09 11:59PM",
  },
  {
    _id: "CNT010",
    cntType: "assignment",
    tagname: "Todo",
    title: "Assignment 5: Async JavaScript",
    descriptions: "Use `fetch` to retrieve API data and display it dynamically on the page. Handle loading states and errors.",
    time: "2025-06-13 11:59PM",
  },
];
