import { LeaveResponse } from '@/api/types/leave';

export const LeaveData: LeaveResponse[] = [
  
    {
        id: '1',
        type: 'Mission Leave',
        startDate: '11 Apr-2025',
        endDate: '12 Apr-2025',
        description: 'Have mission in province',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '2',
        type: 'Sick Leave',
        startDate: '05 May-2025',
        endDate: '07 May-2025',
        description: 'Feeling unwell and need rest',
        tagname: 'Cancelled',
        hasPdf: true,
      },
      {
        id: '3',
        type: 'Personal Leave',
        startDate: '15 Jun-2025',
        endDate: '15 Jun-2025',
        description: 'Personal matters to attend to',
        tagname: 'Rejected',
        hasPdf: false,
      },
      {
        id: '4',
        type: 'Annual Leave',
        startDate: '01 Jul-2025',
        endDate: '05 Jul-2025',
        description: 'Family vacation trip',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '5',
        type: 'Training Leave',
        startDate: '20 Aug-2025',
        endDate: '22 Aug-2025',
        description: 'Attending professional workshop',
        tagname: 'Cancelled',
        hasPdf: false,
      },
      {
        id: '6',
        type: 'Maternity Leave',
        startDate: '01 Sep-2025',
        endDate: '30 Nov-2025',
        description: 'Maternity leave for childbirth',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '7',
        type: 'Paternity Leave',
        startDate: '01 Sep-2025',
        endDate: '15 Sep-2025',
        description: 'Paternity leave for newborn',
        tagname: 'Submitted',
        hasPdf: false,
      },
      {
        id: '8',
        type: 'Study Leave',
        startDate: '10 Oct-2025',
        endDate: '15 Oct-2025',
        description: 'Attending professional certification',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '9',
        type: 'Compassionate Leave',
        startDate: '20 Nov-2025',
        endDate: '22 Nov-2025',
        description: 'Family bereavement',
        tagname: 'Approved',
        hasPdf: false,
      },
      {
        id: '10',
        type: 'Unpaid Leave',
        startDate: '01 Dec-2025',
        endDate: '05 Dec-2025',
        description: 'Personal time off',
        tagname: 'Submitted',
        hasPdf: false,
      },
      {
        id: '11',
        type: 'Medical Leave',
        startDate: '15 Jan-2026',
        endDate: '20 Jan-2026',
        description: 'Medical treatment',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '12',
        type: 'Emergency Leave',
        startDate: '01 Feb-2026',
        endDate: '02 Feb-2026',
        description: 'Family emergency',
        tagname: 'Approved',
        hasPdf: false,
      },
      {
        id: '13',
        type: 'Religious Leave',
        startDate: '10 Mar-2026',
        endDate: '12 Mar-2026',
        description: 'Religious observance',
        tagname: 'Cancelled',
        hasPdf: false,
      },
      {
        id: '14',
        type: 'Sabbatical Leave',
        startDate: '01 Apr-2026',
        endDate: '30 Jun-2026',
        description: 'Professional development',
        tagname: 'Approved',
        hasPdf: true,
      },
      {
        id: '15',
        type: 'Parental Leave',
        startDate: '01 Jul-2026',
        endDate: '31 Jul-2026',
        description: 'Childcare leave',
        tagname: 'Rejected',
        hasPdf: false,
      },
];